
#Example Manifest only, do not apply directly
#Replace bootstrap addresses, Secret names, and namespaces to match your environment.
#Ensure the CA Secrets (*-cluster-ca-cert) exist in the same namespace as MM2.
#Start one replica first; scale up after you verify replication.

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2-bidir
  namespace: kafka
spec:
  replicas: 1
  connectCluster: primary

  clusters:
    - alias: primary
      bootstrapServers: primary-kafka-bootstrap.kafka.svc:9093
      tls:
        trustedCertificates:
          - secretName: primary-cluster-ca-cert
            certificate: ca.crt
      authentication:
        type: tls
        certificateAndKey:
          secretName: mm2-primary
          certificate: user.crt
          key: user.key

    - alias: dr
      bootstrapServers: dr-kafka-bootstrap.kafka.svc:9093
      tls:
        trustedCertificates:
          - secretName: dr-cluster-ca-cert
            certificate: ca.crt
      authentication:
        type: tls
        certificateAndKey:
          secretName: mm2-dr
          certificate: user.crt
          key: user.key

  mirrors:
    # primary -> dr
    - sourceCluster: primary
      targetCluster: dr
      topicsPattern: "lab-.*"
      groupsPattern: "lab-.*"
      sourceConnector:
        config:
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          heartbeats.topic.replication.factor: 3
          sync.topic.configs.enabled: true
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        config:
          emit.checkpoints.enabled: true
          sync.group.offsets.enabled: true
          refresh.groups.interval.seconds: 30
      replicationPolicyClass: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
      replicationPolicySeparator: "."

    # dr -> primary (mirror back the DR-origin topics if needed)
    - sourceCluster: dr
      targetCluster: primary
      topicsPattern: "dr-.*|other-.*"   # <-- be explicit; avoid blindly mirroring everything back
      groupsPattern: "dr-.*"
      sourceConnector:
        config:
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          heartbeats.topic.replication.factor: 3
          sync.topic.configs.enabled: true
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        config:
          emit.checkpoints.enabled: true
          sync.group.offsets.enabled: true
          refresh.groups.interval.seconds: 30
      replicationPolicyClass: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
      replicationPolicySeparator: "."
