apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
  labels:
    app.kubernetes.io/part-of: strimzi-lab
spec:
  kafka:
    version: 3.9.1
    replicas: 3
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    - name: external
      port: 9094
      type: route
      tls: true
      authentication:
        type: tls
    config:
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      log.message.format.version: '3.9'
      inter.broker.protocol.version: '3.9'
    storage:
      type: persistent-claim
      class: gp3-csi
      size: 30Gi
      deleteClaim: false
    authorization:
      type: simple
      superUsers:
      - CN=demo-zk-superuser
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: gp3-csi
      size: 50Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  authentication:
    type: tls